Vagrant.configure("2") do |config|
  config.vm.box = "almalinux/9"

  [
    ["alma9-1", "192.168.40.11"],
    ["alma9-2", "192.168.40.12"]
  ].each do |name, private_ip|
    config.vm.define name do |node|
      node.vm.hostname = name

      # Internal network only
      node.vm.network "private_network",
        ip: private_ip,
        libvirt__network_name: "rhcsa-internal-net"

      node.vm.provider :libvirt do |lv|
        lv.memory = 2048
        lv.cpus = 2
        lv.storage_pool_name = "qemu-storage"

        lv.storage :file, size: '10G', device: 'vdb'
        lv.storage :file, size: '5G', device: 'vdc'

        lv.storage :file,
          device: :cdrom,
          bus: :ide,
          type: :raw,
          path: '/mnt/data/ISO/AlmaLinux-9.7-x86_64-dvd.iso'
      end
    end
  end
end
