name: Terraform CI/CD with Submodule

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch
    paths:
      - 'aws-tf-1/**' # Trigger only when changes are made in the aws-tf-1 directory or its subdirectories

env:
  AWS_REGION: eu-west-2 # Specify your AWS region here

jobs:
  terraform:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout code including submodules
      uses: actions/checkout@v4
      with:
        submodules: true # This line tells the action to clone submodules

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.4 # Specify the Terraform version you want to use

    - name: Terraform Init
      id: init
      # Navigate to your submodule directory before running Terraform commands
      run: |
        cd aws-tf-1 # Changed path to your submodule directory
        terraform init

    - name: Terraform Plan
      id: plan
      # Navigate to your submodule directory before running Terraform commands
      run: |
        cd aws-tf-1 # Changed path to your submodule directory
        terraform plan -no-color

    # Add a conditional apply step
    # This step will now only run when the workflow is triggered by changes in aws-tf-1/**
    - name: Terraform Apply
      # Removed the explicit if condition as the trigger already handles this
      run: |
        cd aws-tf-1 # Changed path to your submodule directory
        terraform apply -auto-approve

