name: Deploy and Destroy Azure Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'azure-tf-1/**' # Trigger only if files in `azure-tf-1` change

  workflow_dispatch: # Allow manual triggering
    inputs:
      destroy:
        description: 'Set to true to run terraform destroy. Leave false or empty to run plan/apply.'
        required: false
        type: boolean
        default: false

env:
  AZURE_REGION: UK South

jobs:
  terraform_apply:
    name: Terraform Plan & Apply for Azure
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_dispatch' && github.event.inputs.destroy != 'true')

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate to Azure
      run: |
        az login --service-principal \
          --username "${{ secrets.AZURE_CLIENT_ID }}" \
          --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
          --tenant "${{ secrets.AZURE_TENANT_ID }}"

    - name: Set Subscription
      run: |
        az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.4

    - name: Terraform Init
      run: |
        cd azure-tf-1
        terraform init

    - name: Terraform Plan with Debug
      run: |
        cd azure-tf-1
        terraform plan -var="ssh_public_key=${{ secrets.AZURE_SSH_PUBLIC_KEY_1 }}" \
                   -var="azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                   -no-color | tee plan.log
        cat plan.log  # Debugging step to check logs        
        
    - name: Terraform Apply
      run: |
        cd azure-tf-1
        terraform apply -auto-approve -var="azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                        -var="ssh_public_key=${{ secrets.AZURE_SSH_PUBLIC_KEY_1 }}" \
                        -no-color

  terraform_destroy:
    name: Terraform Destroy for Azure
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' &&
      github.event.inputs.destroy == 'true'

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set SSH Public Key Variable
      run: |
        echo 'ssh_public_key = "${{ secrets.AZURE_SSH_PUBLIC_KEY_1 }}"' > terraform.tfvars

    - name: Authenticate to Azure
      run: |
        az login --service-principal \
          --username "${{ secrets.AZURE_CLIENT_ID }}" \
          --password "${{ secrets.AZURE_CLIENT_SECRET }}" \
          --tenant "${{ secrets.AZURE_TENANT_ID }}"

    - name: Set Subscription
      run: |
        az account set --subscription "${{ secrets.AZURE_SUBSCRIPTION_ID }}"

    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.11.4

    - name: Terraform Init (Destroy)
      run: |
        cd azure-tf-1
        terraform init

    - name: Terraform Destroy
      run: |
        cd azure-tf-1
        terraform destroy -auto-approve \
           -var="azure_subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
           -var="ssh_public_key=${{ secrets.AZURE_SSH_PUBLIC_KEY_1 }}"
